### ISSUE TITLE
System.env\1 for access for each request.

### ISSUE THREAD

**Issue by erneestoc** [thechangelog/changelog.com#118]
Instead of calling the system for each Craisin module request, you should use a module constant, or an Application.get_env setting.. 

``` elixir
defmodule Craisin do
  use HTTPoison.Base

  require Logger
  @cm_api_token (System.get_env("CM_API_TOKEN") || "")
  defp auth do
    Base.encode64((@cm_api_token) <> ":x")
  end
### etc... 
end
```

**Comment by jerodsanto** [comment]
@erneestoc I actually was using a module attribute previously, but ran into issues with it when deploying to prod because they're evaluated at compile time and the env vars aren't available until run time with our deployment scheme (I'm really bad at Elixir compile vs runtime stuff so please correct me if that's wrong).

I guess my question would be: is calling the system each time a lot slower than doing it once? (I definitely see how it's wasteful, but I'm not sure if it's wasteful enough to matter).

**Comment by gerhard** [comment]
@jerodsanto we could easily make this env var available at compile time

**Comment by jerodsanto** [comment]
@gerhard ok let's do it! Holler when it's available and I'll make this improvement.

**Comment by gerhard** [comment]
Since we use `Mix.Config` for all other configuration values, would it make more sense to adopt the same approach in this module as well?
