### ISSUE TITLE
Allow faster playback

### ISSUE THREAD

**Issue by sotojuan** [thechangelog/changelog.com#139]
Let us play the audio at 1.25x or 1.5x speed! I can help out with this in a PR if it sounds good, but I don't know where to fit it in the player.

**Comment by jerodsanto** [comment]
🤔

Part of me hates this and part of me understands it 💯

@adamstac what's your take on this?

**Comment by sotojuan** [comment]
FWIW I do this on the iPhone podcasts app a lot, so maybe I'm just used to it. I get why something like this is best left to dedicated podcast apps though.

**Comment by jerodsanto** [comment]
@sotojuan I've been thinking about this more and I think we should do it as a hidden feature! It's not something that we necessarily want to promote in the player UI (where space is limited anyhow and we have future ideas that will use what space is available), but if power users want to speed up our shows, I say let's let them (like you said, this is something you can do in podcast apps anyhow).

Would you still want to work on it if it's only available via a keyboard shortcut? We already have a few wired up (esc to stop, space bar to play/pause). I'd imagine it would have 3 speeds that would cycle each time you hit the shortcut:

1. 1x (default)
2. 1.5x
3. 2x

Alternatively, we could use a different key for each speed, but cycling seems more straight forward to me.

What do you think?

_(If you're interested, hold off a bit as we're about to land some big changes to the `player.js` code when the embeds branch gets merged.)_

**Comment by sotojuan** [comment]
> Would you still want to work on it if it's only available via a keyboard shortcut?

Yep!

> What do you think?

Sounds good. I'll watch the repository for the changes to `player.js` and when it looks good to hack on I'll get started. Thanks!

**Comment by jerodsanto** [comment]
Awesome! Once #138 gets merged you should be good to go 👍

Curious: if you listen in Podcasts app often, what is your use case when listening on the website?

**Comment by sotojuan** [comment]
Usually at work I already have my headphones plugged to my computer and don't want to take my phone out. I've also linked people to specific Changelog episodes and they've asked me how to play it faster. 

I figured since you allow skipping by 15 seconds (ubiquitous in podcast apps), faster playback would make sense.

Note that I'm not saying that The Changelog is too slow by default, but a lot of people seem to be used to 1.25-1.50x playback speed for podcasts.

**Comment by jerodsanto** [comment]
That makes a lot of sense, thanks for the insight (and thanks for sharing our shows with people 😁). 

I just merged the embeds branch so the overhaul to the player is complete. The files you'll want to fuss with are:

1. [web/static/app/components/audio.js](https://github.com/thechangelog/changelog.com/blob/master/web/static/app/components/audio.js)
2. [web/static/app/components/onsite_player.js](https://github.com/thechangelog/changelog.com/blob/master/web/static/app/components/onsite_player.js)

Holler if you have any questions!

**Comment by sotojuan** [comment]
I've been quiet but have started work on this. I just need some audio file in the DB to test my code with. What can I do about that?

**Comment by jerodsanto** [comment]
Testing it first is probably worth the effort 😄. A couple of thoughts:

1. There was some work done in creating seed data in #135, but I haven't merged it yet because he was still working on it. You can see if that works for you (I'm happy to merge it if it's useful in its current state)
2. You can manually override the html on the anchor in the `_play_bar` partial to return one of our CDN urls (https://cdn.changelog.com/uploads/podcast/225/the-changelog-225.mp3) then clicking Play from the play bar (you'd still need this to draw somehow) would launch the player and load that mp3
3. There is a sound file in the repo (`web/static/assets/california.mp3`) that you can use. It's a pretty good song, too 😉

Another note: there is something funky with Cowboy and range requests (I don't recall the particulars) so Chrome doesn't seek properly (Safari and Firefox seem OK) when serving an mp3 locally. For this reason I tend to use CDN'd mp3s for that kind of testing (it also has the benefit of being more representative of real-world use). Not sure if that'll affect playback rate or not.

Any of those work for you?
