### ISSUE TITLE
Margin issue on featured podcast on the homepage

### ISSUE THREAD

**Issue by adamstac** [thechangelog/changelog.com#140]
Using Chrome — on initial page load and other times with navigating back to the homepage from other pages of the site, the margin/padding above and below the featured show is off.

This could be from Turbolinks, not sure.

**Comment by adamstac** [comment]
@codyjames you may be able to help here too since this was more of your thing.

**Comment by jerodsanto** [comment]
I can't reproduce this. I definitely see some quotes having bigger margins than others (which is on purpose because they have less lines of text, I believe), and sometimes when you return to the homepage a different quote replaces one that was there previously, but I can't make it so the same show's quote has different spacing around it when returning to the home page.

**Comment by adamstac** [comment]
Incorrect margin:

![screen shot 2016-12-07 at 3 55 01 pm](https://cloud.githubusercontent.com/assets/2933/20988292/c56f5702-bc95-11e6-9ee5-1fe8c05b9942.png)

Refreshed with correct margin:

![screen shot 2016-12-07 at 3 55 43 pm](https://cloud.githubusercontent.com/assets/2933/20988312/da8df404-bc95-11e6-8cc1-ce0eb5949b23.png)
