### ISSUE TITLE
Add a JSON Feed

### ISSUE THREAD

**Issue by jerodsanto** [thechangelog/changelog.com#196]
Our news feed lives at `https://changelog.com/feed` and serves a typical RSS/xml file. In addition to this, we'd like to add a [JSON Feed](https://jsonfeed.org/version/1) for those folks who prefer the newer format.

The main reason we want to do this is because we agree with this sentiment:

> Our hope is that, because of the lightness of JSON and simplicity of the JSON Feed format, developers will be more attracted to developing for the open web.

Perhaps nobody will use this feed, but we want it to be there just in case they do.

This feed should live at `https://changelog.com/feed.json` and should conform to the spec.

**Comment by joebew42** [comment]
Hi all, I'm working on this feature and I've some questions to ask to you.

- I noticed that the `Episode` and `Post` item must have their own way to be mapped into a JSON feed item (the same way as XML/RSS do). I am wondering what other item I can use to "test" the default mapping (basically this should happen when we are trying to map items different from `Episode` and `Post`). I looked at the test (`feed_controller_test.exs`) but there we are testing only for `Episode` and `Post`. So it seems that the function [`render_item(item = %{object: nil}, assigns)`](https://github.com/thechangelog/changelog.com/blob/20d5660d9f5e6981f6f56c9405a207a3c3d0b8b4/lib/changelog_web/views/feed_view.ex#L14) is not tested.

- How to format the `description` of an `Episode`? Should we have to maintain the same way of the [XML/RSS feed item](https://github.com/thechangelog/changelog.com/blob/master/lib/changelog_web/templates/feed/_episode_description.xml.eex)? Or may we can consider to use a plain text representation (`content_text`)
- Can we create a `news.json.eex` instead of a render function in the `feed_view.ex`?

Thank You very much for all your responses :+1:

**Comment by jerodsanto** [comment]
👋 

1. A "regular" item is a `%Changelog.NewsItem{}` struct that doesn't have an attached `object` (Episode or Post). I believe you are correct and this isn't being tested. We need to fix that 😄 
2. I think for the JSON feed we can keep it simple and just render the `news_item.story` (which is a field that contains Markdown text) as html for `content_html` and again as text for `content_text`. No need to specially craft different descriptions for episodes and posts. However, for episodes we _will_ want to add the audio as an attachment (which you can see in action under the Podcast examples in the spec)
3. I haven't tried it yet (please do and report back!) but I don't think there's support for JSON templates like there is for xml. All of the JSON rendering I've done has been via view functions. That being said, maybe it'd be nice for this to have a separate module, since it's quite different than the rest of the feed rendering. `ChangelogWeb.JsonFeedView`, perhaps?

Hope this helps!

**Comment by joebew42** [comment]
Hi @jerodsanto , thank you for all the responses. I would like to know if it could be better to create another controller, like `json_feed_controller`? What do you think?

**Comment by jerodsanto** [comment]
@joebew42 go for it and we'll see how it looks/feels.
