### ISSUE TITLE
Indexes

### ISSUE THREAD

**Issue by keslert** [thechangelog/changelog.com#243]
I'm trying to understand when to add an index to a table and when it's unnecessary. Specifically, the posts table has frequent queries that include published and published_at, but neither are indexed. So how do you go about deciding what needs an index?

**Comment by jerodsanto** [comment]
Good question! I'm not super systematic about how/where to add indexes. Generally speaking, if a column will be queried often, it'll get one.

In the case of `posts`, _most_ of the time we are looking them up by `slug`, so that is an obvious index opportunity. That query may be combined with `published` and `published_at`, but PG is smart enough to use the `slug` index first, which renders the others moot.

That being said, `posts` is not a write-heavy table, so it would be completely reasonable to add another index to it. We just haven't experienced slow responses on `/posts` or anything that would make me want to speed things up there.

**Comment by keslert** [comment]
I'd wondered if PG was smart enough to use the `slug` index first, so thanks for the clarification on that. Any insight on whether an index makes a difference for ordering on a date/datetime? For example when fetching all `posts` and ordering by `published_at`.

**Comment by jerodsanto** [comment]
If you create the index correctly, yes. Read up:

https://devcenter.heroku.com/articles/postgresql-indexes#b-trees-and-sorting

(that entire article is 👌)

**Comment by keslert** [comment]
That article is great—thanks for sharing! Helped a lot with my understanding.
