### ISSUE TITLE
RSS access to older episodes

### ISSUE THREAD

**Issue by gliptak** [thechangelog/changelog.com#284]
Currently the RSS feed

https://changelog.com/podcast/feed

goes back to

https://changelog.com/podcast/244

Older episodes are available on the site like:

https://changelog.com/podcast/243

Could older issues be also included in the feed or maybe an archive feed could be made available?

I switched over from the 5by5 feed and a number of episodes no longer listed ...

**Comment by jerodsanto** [comment]
@gliptak we changed that (limit 100) recently because our feeds were too big for certain podcast directories' standards. Unfortunately, there's no pagination standard for RSS, but I know there are some folks working on one for podcasts in particular.

I might be up for an archive feed, but I'm curious what your use case is?

**Comment by gliptak** [comment]
I was chipping away at the old episodes and still was in double digits ...

If you see value in having old episodes on the website, having an old (full?) RSS would also provide similar value.

**Comment by jerodsanto** [comment]
@gliptak I added support for [RFC 5005's page feeds](https://tools.ietf.org/html/rfc5005#section-3). Not all podcast clients support this feature, but some do.

Does that get you were you want to go?

**Comment by gliptak** [comment]
yes, this worked (I had delete/reload the podcast)

thank you for reworking this quickly @jerodsanto

**Comment by calaway** [comment]
I'm also looking to access episodes older than the most recent 100 on the RSS feed. @jerodsanto, I see that @gliptak said you addressed his issue, but I don't see how, since [the RSS feed](https://changelog.com/podcast/feed) is only showing the last 100 (currently back to episode 270).

My use case is that I find the podcast incredibly valuable for learning about dev concepts on my drive to work. For example, I'm going to be working with HTTP/2 soon, so I want to listen to [episode #161, The HTTP/2 Spec with Ilya Grigorik](https://changelog.com/podcast/161), but it is unfortunately not available on the feed.

Please let me know if I'm missing something, or if there is any other way I can access this on my regular podcast app (BeyondPod).

**Comment by jerodsanto** [comment]
@calaway our feed supports pagination past the most recent 100 episodes, but sadly not all podcast clients support that feature. 

I hate to ask you to switch clients just for us, but I also don't want to roll a new feed just for this one reason.

Maybe reach out to the BeyondPod folks and ask them to add [paged feeds](https://tools.ietf.org/html/rfc5005#section-3) support? I'm happy to help you make that case or help them with the implementation if they're interested in that.

**Comment by calaway** [comment]
Okay, I understand now. I didn't know that paged feeds were a thing. For anyone else who is looking at this, notice that you can see older episodes by appending a query param, e.g. https://changelog.com/podcast/feed?page=2.

My old podcast app, BeyondPod, doesn't support this, but they have been lagging in updates and features for a while now. I think this will be a good opportunity to try out an open source podcast app that's been on my radar for a while, AntennaPod. So far it looks like it is handling your paged feed just fine.

Thank you for your support @jerodsanto. Thanks for all you guys do for us developers and for the open source community!

**Comment by jerodsanto** [comment]
@calaway awesome, hadn't heard of [AntennaPod](https://antennapod.org) previously but we love open source apps, especially when they support features like this!

_(It'd be cool to create a list of podcast clients that support paged feeds...)_

I pinned this issue so that other folks can find it more easily in the future.

Thanks for listening! 💚💚💚

**Comment by jcs224** [comment]
Since this is pinned, I thought I'd pitch a new PWA podcast app I just (re)built in Vue, and it supports paginated feeds. I actually used the previous Changelog feed to help me build out the pagination feature! Mostly as a demonstration of what's possible as a PWA now, but I do use it for all my podcast listening these days! Including several Changelog shows, of course :smiley: 

https://github.com/podrain/podrain

**Comment by gerhard** [comment]
Do we still want to keep this issue pinned @jerodsanto?

**Comment by jerodsanto** [comment]
This is no longer true because we ended up putting ALL the episodes back in the feeds (until more podcast apps/directories support paged feeds, which they may never). Unpinning
