### ISSUE TITLE
Broken link in Changelog Weekly 253

### ISSUE THREAD

**Issue by jerodsanto** [thechangelog/changelog.com#289]
The news item:

https://changelog.com/news/1mNQ

The URL:

https://wiki.postgresql.org/wiki/Don't_Do_This

The way it's rendered in Weekly:

https://wiki.postgresql.org/wiki/Don't_Do_This

The way it's rendered in Email:

https://wiki.postgresql.org/wiki/Don&#39;t_Do_This

**Comment by sunndeath** [comment]
Could you please assign this task on me?

**Comment by jerodsanto** [comment]
@sunndeath assigned! Let me know if I can help along the way ✊

**Comment by sunndeath** [comment]
> @sunndeath assigned! Let me know if I can help along the way ✊

Hi!
I apologize for the wasting time. Unfortunately I can't participate in your project because I have the problem with your repository on my windows machine:
![image](https://user-images.githubusercontent.com/8881978/82811677-fec91f80-9e99-11ea-8a49-d2c1027e60be.png)

Please, unassign this issue from me and I'm sorry again.

**Comment by gerhard** [comment]
In the interest of [Kaizen 7](https://shipit.show/70) (ships September 14), closing this now. If we still think that it's relevant, it's OK to re-open.

改善
