### ISSUE TITLE
Playback Speed

### ISSUE THREAD

**Issue by kyllionaire** [thechangelog/changelog.com#352]
Hi. 
I wanted to suggest a variable playback speed option. 
Thanks!

**Comment by jerodsanto** [comment]
This exists! It's just undocumented and not in the UI anywhere.

Type `s` (for speed) while the player is active and it will crank the playback rate by `.25` intervals until it hits `1.75`, at which point it goes back down to `1`.

I can't recall why we set that threshold, but I _believe_ it's because the chipmunk effect is pretty dramatic and darn near unlistenable at `2.0` and above (we're relying on the browser's built-in playback rate adjustments so we can't control the implementation of how it sounds).

Hope this helps and I'm happy to make the feature better if you have specific requests!

**Comment by gerhard** [comment]
Do we still want to keep this issue pinned @jerodsanto?
