### ISSUE TITLE
Renaming "Master" feed

### ISSUE THREAD

**Issue by xmulligan** [thechangelog/changelog.com#366]
the software industry has a lot of non inclusive terms that are unclear to English as a second language speakers and can be harmful to minorities in tech. One of those words is "Master". It would be great to see Changelog as a media outlet take a lead on this industry change and rename their main podcast feed to a more inclusive alternative like main, original, or source.

See:
https://inclusivenaming.org/
https://www.nytimes.com/2021/04/13/technology/racist-computer-engineering-terms-ietf.html

**Comment by jerodsanto** [comment]
@xmulligan I appreciate your nudge on this and I understand the concern, but this is not a change we're interested in making.

I'm sympathetic to the argument that we should stop using master/slave (relationship) terminology in tech. Because gross. However, I don't think it's necessary to cede "master" altogether. It's a useful word with many contexts.

- A master is a teacher
- A master is an expert
- A master is an original
- A master is a commander
- A master is a [chief](https://en.wikipedia.org/wiki/Master_Chief_(Halo)) 😜

There's no reason to take offense to a "master's degree", because there are no slave degrees. There's no reason to take offense to a "master sommelier", because there are no slave sommeliers. There's no reason to take offense to a "master boot record", because there are no slave boot records.

We chose the name "Changelog Master Feed" as an homage to the [mastering of records](https://en.wikipedia.org/wiki/Mastering_(audio)) (the feed's cover art is a record, btw, if you haven't drawn that connection yet). 

Our audience is smart, sophisticated, and able to understand extremely complex topics like idempotence, the law of demeter, and SOAP (😏). I think we can trust that our _completely-appropriate-and-not-racist-in-any–way_ use of "master" is received by them with equivalent grace and understanding.

**Comment by xmulligan** [comment]
@jerodsanto thanks for your through response. I appreciate your perspective. Would you be willing to updated the name of the default branch in the repo?

https://github.com/github/renaming
