### ISSUE TITLE
"Changelog Interviews" pods do not play at all on the website

### ISSUE THREAD

**Issue by ju-la-berger** [thechangelog/changelog.com#457]
Hello there,

all the "Changelog Interviews" podcasts **are not playing at all on the website**. (An example is the latest episode https://changelog.com/podcast/534 but it affects all others as well). The "play" button just keeps spinning.

The "Changelog News" podcasts work fine as well as the others (e.g. "JS Party" & "Go Time") I tried. So, it seems to be related only to the main podcast series.

It does not make a difference if I am logged in (on the website) or not. I tried on my desktop using Chromium as well as on my iPhone using Mobile Safari. I tried emptying the cache and so on.

Thanks in advance and for your work in general!

**Comment by gerhard** [comment]
Thanks for reporting this!

The URL is incorrect. It should be https://cdn.changelog.com/uploads/podcast/534/the-changelog-534.mp3 instead of https://cdn.changelog.com/uploads/podcast/534/changelog-interviews-534.mp3

I suspect that this commit introduced the issue: https://github.com/thechangelog/changelog.com/commit/f0f02d305c92c7b2c83ef5ba08988088eb556175 . Running this against the prod db will have updated all slugs, not just the `news` episodes.

**Comment by jerodsanto** [comment]
Thanks for the report! Should be fixed now

**Comment by gerhard** [comment]
👍 https://github.com/thechangelog/changelog.com/commit/60fd7eb97853bec14ad140e4f7621ddd3006edda
