### ISSUE TITLE
Episode Page: last element doesn't fit in podcast menu on desktop

### ISSUE THREAD

**Issue by eahlberg** [thechangelog/changelog.com#481]
In Firefox and Chrome on desktop:

![image](https://github.com/thechangelog/changelog.com/assets/2501850/f1b7055d-0ccf-4bb5-8c5a-8adbbc990654)

If you're open to a PR I'll give it a go.

**Comment by jerodsanto** [comment]
Hmm I'm not seeing the issue on Firefox or Chrome (macOS). It appears that maybe our fonts aren't loading for you, and that's why the text is too wide? It should be "DIN 2014 Narrow" for the "Share" text. Can you check that and see if maybe it's the culprit?

**Comment by eahlberg** [comment]
Oh, you're right, the font used is "DejaVu Sans". It looks like the container's width is hard coded, I guess it would be possible to fix the issue by making the container's width dynamic but I don't know whether that's suitable.

**Comment by jerodsanto** [comment]
Are there any failures in the console showing fonts failing to load? Or do you have any user scripts running that would override our font settings?

**Comment by eahlberg** [comment]
Both the network tab and the console looks fine, I can't see that there's even a request for "DIN 2014 Narrow".

FYI: the page looks fine on macOS but the font rendered is "Arial Narrow", which I guess I don't have on my primary laptop.

**Comment by eahlberg** [comment]
A fix on my part was to install e.g. [Liberation Sans Narrow](https://github.com/liberationfonts/liberation-sans-narrow) which apparently works as a fallback for "Arial Narrow", but I guess it still might be an issue for devices which do not have a fallback font.

**Comment by jerodsanto** [comment]
Weird that your browser wouldn't just download the web font... I wonder if maybe I removed that font from our head because it was used pretty much nowhere and most systems have it pre-installed or something? Gotta dig more...

**Comment by jerodsanto** [comment]
Ok so the Din Narrow thing was a red herring: I removed it a long time ago so everyone was pretty much using Arial Narrow except on systems like yours that didn't have it.

Our problem was assuming there'd be a narrow font available, which I don't think you can safely assume. I changed two things:

1.  I added some more narrow fallback fonts for systems that might have them before falling all the way back to `serif`
2. I made the play bar 600px wide instead of 540, ensuring it'd have enough space even for non-narrow fonts

We're excited to revamp our episode pages and get rid of this entire current implementation. But until then, hope that takes care of the display bug!

**Comment by eahlberg** [comment]
Cool, looks good!
